module DraftjsHtml
  # This class manages the depth and nesting of the myriad HTML tags generated by DraftjsHtml::ToHtml.
  # It is intended to be a private implementation detail.
  class HtmlDepth # :nodoc:
    BLOCK_TYPE_TO_HTML_WRAPPER = {
      'code-block' => 'pre',
      'ordered-list-item' => 'ol',
      'unordered-list-item' => 'ul',
    }.freeze

    def initialize(body)
      @current_depth = 0
      @body = body
      @previous_parents = [body.parent]
      @nesting_roots = [body.parent.name]
    end

    def apply(block)
      return unless nesting_root_changed?(block) || depth_changed?(block)

      if deepening?(block)
        deepen(block)
      elsif rising?(block) && still_nested?(block)
        rise(times: @current_depth - block.depth)
      elsif rising?(block)
        rise(times: @current_depth - block.depth)
        pop_parent
      elsif still_nested?(block)
        push_parent(block)
      elsif nested?
        pop_parent
      end

      @current_depth = block.depth
    end

    private

    def deepen(block)
      tagname = BLOCK_TYPE_TO_HTML_WRAPPER[block.type]
      @previous_parents << @body.parent
      @nesting_roots << tagname
      @body.parent = @body.parent.last_element_child
      push_parent(block)
    end

    def push_parent(block)
      tagname = BLOCK_TYPE_TO_HTML_WRAPPER[block.type]
      node = create_child(tagname)
      @previous_parents << @body.parent
      @body.parent = node
    end

    def rise(times:)
      times.times do
        begin
          pop_parent
        end while @body.parent.name != @nesting_roots.last
        @nesting_roots.pop
      end
    end

    def pop_parent
      @body.parent = @previous_parents.pop
    end

    def create_child(tagname)
      @body.parent.add_child(@body.doc.create_element(tagname))
    end

    def nested?
      @body.parent.name != 'body'
    end

    def still_nested?(block)
      BLOCK_TYPE_TO_HTML_WRAPPER[block.type]
    end

    def depth_changed?(block)
      block.depth != @current_depth
    end

    def nesting_root_changed?(block)
      @body.parent.name != BLOCK_TYPE_TO_HTML_WRAPPER[block.type]
    end

    def rising?(block)
      @current_depth > block.depth
    end

    def deepening?(block)
      @current_depth < block.depth
    end
  end
end
